aws_region               = "us-east-2"
ecs_task_definition_name = "pants-or-shorts-runner"
ecs_container_name       = "pants-or-shorts"
ecs_cluster_name         = "pants-or-shorts-cluster"
ecs_service_name         = "pants-or-shorts-service"