FROM --platform=linux/amd64 node:18-alpine
RUN ["npm" ,"install", "-g","pnpm"]
COPY package.json /pants-or-shorts/
COPY . /pants-or-shorts
WORKDIR /pants-or-shorts
RUN ["pnpm", "install"]
CMD ["pnpm", "dev"]
EXPOSE 8000